### ISSUE TITLE
not able to install blasr

### ISSUE THREAD

**Issue by alexfrieden** [PacificBiosciences/blasr#187]
downloaded latest version.

OS is:

``` 
     $  cat /proc/version
     Linux version 3.13.0-48-generic (buildd@orlo) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015
```

Ran the following:

```
sudo apt-get install libhdf5-dev
sudo apt-get install libconfig-dev
```

Seemed to work.  However, I keep getting the following:
```
In file included from DatasetCollection.hpp:8:0,
                 from DatasetCollection.cpp:1:
HDFGroup.hpp:9:24: fatal error: H5Location.h: No such file or directory
 #include <H5Location.h>
                        ^
compilation terminated.
```
In many different modules even though I even set my H5 lib and inc.  

```
$ echo $HDF5_INC
/usr/include/hdf5.h
$ echo $HDF5_LIB
/usr/lib/x86_64-linux-gnu/
```

Any thoughts why this is not installing?  Thanks!

**Comment by pb-cdunn** [comment]
It's probably an old version of HDF5.
* https://github.com/PacificBiosciences/blasr/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+H5Location.h%3A+No+such+file+or+directory+

**Comment by alexfrieden** [comment]
I installed HDF5 today using the commands I listed.  Those should be latest ones.  What version should I use for proper hdf5?

**Comment by pb-cdunn** [comment]
* What were your arguments to `configure.py`?
* What is in `defines.mk` (generated by configure.py)?
* What commit of **blasr**? (`git rev-parse HEAD`)

**Comment by alexfrieden** [comment]
commit version:
```
$ git rev-parse HEAD
a993270655aa30cd1e6572b3b3fc149400685725
```
contents of defines.mk
```
$ cat defines.mk
LIBPBDATA_LIB        ?= /home/ubuntu/alex/blasr/libcpp/pbdata
LIBBLASR_LIBFLAGS    ?= -lblasr
HDF5_LIB             ?= /usr/lib/x86_64-linux-gnu/
DL_LIBFLAGS          ?= -ldl
HDF5_INC             ?= /usr/include/hdf5.h
LIBPBDATA_INC        ?= /home/ubuntu/alex/blasr/libcpp/pbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
LIBPBIHDF_INC        ?= /home/ubuntu/alex/blasr/libcpp/hdf
LIBBLASR_LIB         ?= /home/ubuntu/alex/blasr/libcpp/alignment
SHELL                ?= bash
RT_LIBFLAGS          ?= -lrt
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
LIBPBDATA_LIBFLAGS   ?= -lpbdata
ZLIB_LIBFLAGS        ?= -lz
LIBBLASR_INC         ?= /home/ubuntu/alex/blasr/libcpp/alignment
PTHREAD_LIBFLAGS     ?= -lpthread
NOPBBAM              ?= 1
LIBPBIHDF_LIB        ?= /home/ubuntu/alex/blasr/libcpp/hdf
```

was using travis.sh so configure is:
```
./configure.py --shared --sub --no-pbbam HDF5_INC=${HDF5_INC} HDF5_LIB=${HDF5_LIB}
```

**Comment by pb-cdunn** [comment]
HDF5_INC             ?= /usr/include/hdf5.h

That should be a directory, not a file. Check your gcc compile line. You probably have something like `-I/usr/include/hdf5.h`.

**Comment by alexfrieden** [comment]
changed it to /usr/include/

However still getting errors when running travis.sh:
```
In file included from HDFData.hpp:7:0,
                 from BufferedHDF2DArray.hpp:12,
                 from BufferedHDF2DArray.cpp:1:
HDFGroup.hpp:9:24: fatal error: H5Location.h: No such file or directory
 #include <H5Location.h>
                        ^
In file included from HDFData.hpp:7:0,
                 from HDFArray.hpp:10,
                 from HDFAlnGroupGroup.hpp:5,
                 from HDFAlnGroupGroup.cpp:1:
```

Contents of defines.mk:
```
$ cat defines.mk
LIBPBDATA_LIB        ?= /home/ubuntu/alex/blasr/libcpp/pbdata
LIBBLASR_LIBFLAGS    ?= -lblasr
HDF5_LIB             ?= /usr/lib/x86_64-linux-gnu/
DL_LIBFLAGS          ?= -ldl
HDF5_INC             ?= /usr/include/
LIBPBDATA_INC        ?= /home/ubuntu/alex/blasr/libcpp/pbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
LIBPBIHDF_INC        ?= /home/ubuntu/alex/blasr/libcpp/hdf
LIBBLASR_LIB         ?= /home/ubuntu/alex/blasr/libcpp/alignment
SHELL                ?= bash
RT_LIBFLAGS          ?= -lrt
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
LIBPBDATA_LIBFLAGS   ?= -lpbdata
ZLIB_LIBFLAGS        ?= -lz
LIBBLASR_INC         ?= /home/ubuntu/alex/blasr/libcpp/alignment
PTHREAD_LIBFLAGS     ?= -lpthread
NOPBBAM              ?= 1
LIBPBIHDF_LIB        ?= /home/ubuntu/alex/blasr/libcpp/hdf
```

**Comment by pb-cdunn** [comment]
Try `HDF5_INC=/usr/include/hdf5`.

**Comment by alexfrieden** [comment]
Thanks for the fast response:  Similar error:
```
$ ./travis.sh
+ ./configure.py --shared --sub --no-pbbam HDF5_INC=/usr/include/hdf5 HDF5_LIB=/usr/lib/x86_64-linux-gnu/
`uname`
Linux
writing to '/home/ubuntu/alex/blasr/defines.mk':
"""
LIBPBDATA_LIB        ?= /home/ubuntu/alex/blasr/libcpp/pbdata
LIBBLASR_LIBFLAGS    ?= -lblasr
HDF5_LIB             ?= /usr/lib/x86_64-linux-gnu/
DL_LIBFLAGS          ?= -ldl
HDF5_INC             ?= /usr/include/hdf5
LIBPBDATA_INC        ?= /home/ubuntu/alex/blasr/libcpp/pbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
LIBPBIHDF_INC        ?= /home/ubuntu/alex/blasr/libcpp/hdf
LIBBLASR_LIB         ?= /home/ubuntu/alex/blasr/libcpp/alignment
SHELL                ?= bash
RT_LIBFLAGS          ?= -lrt
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
LIBPBDATA_LIBFLAGS   ?= -lpbdata
ZLIB_LIBFLAGS        ?= -lz
LIBBLASR_INC         ?= /home/ubuntu/alex/blasr/libcpp/alignment
PTHREAD_LIBFLAGS     ?= -lpthread
NOPBBAM              ?= 1
LIBPBIHDF_LIB        ?= /home/ubuntu/alex/blasr/libcpp/hdf
"""
----
+ make -j4 init-submodule
make update-submodule
make[1]: Entering directory `/home/ubuntu/alex/blasr'
git submodule update --init
make[1]: Leaving directory `/home/ubuntu/alex/blasr'
make configure-submodule
make[1]: Entering directory `/home/ubuntu/alex/blasr'
make -f /home/ubuntu/alex/blasr//sub.mk configure-submodule
make[2]: Entering directory `/home/ubuntu/alex/blasr'
cd libcpp && ./configure.py
uname -s
uname='Linux'
writing to 'defines.mk'
"""

SH_LIB_EXT           := .so

HDF5_INC:=/usr/include/hdf5
HDF5_LIB:=/usr/lib/x86_64-linux-gnu/
LIBPBDATA_INC     ?=../pbdata
LIBPBIHDF_INC     ?=../hdf
LIBBLASR_INC      ?=../alignment
LIBPBDATA_LIB     ?=../pbdata
LIBPBIHDF_LIB     ?=../hdf
LIBBLASR_LIB      ?=../alignment

# Use PREFIX dir, if available.
INCLUDES      += ${PREFIX_INC}
LIBS          += ${PREFIX_LIB}
"""
make[2]: Leaving directory `/home/ubuntu/alex/blasr'
make[1]: Leaving directory `/home/ubuntu/alex/blasr'
make build-submodule
make[1]: Entering directory `/home/ubuntu/alex/blasr'
make -C libcpp
make[2]: Entering directory `/home/ubuntu/alex/blasr/libcpp'
make libpbdata
make[3]: Entering directory `/home/ubuntu/alex/blasr/libcpp'
make -C /home/ubuntu/alex/blasr/libcpp//pbdata libconfig.h
make[4]: Entering directory `/home/ubuntu/alex/blasr/libcpp/pbdata'
make[4]: `libconfig.h' is up to date.
make[4]: Leaving directory `/home/ubuntu/alex/blasr/libcpp/pbdata'
make -C /home/ubuntu/alex/blasr/libcpp//pbdata all
make[4]: Entering directory `/home/ubuntu/alex/blasr/libcpp/pbdata'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/home/ubuntu/alex/blasr/libcpp/pbdata'
make[3]: Leaving directory `/home/ubuntu/alex/blasr/libcpp'
make libpbihdf
make[3]: Entering directory `/home/ubuntu/alex/blasr/libcpp'
make -C /home/ubuntu/alex/blasr/libcpp//hdf all
make[4]: Entering directory `/home/ubuntu/alex/blasr/libcpp/hdf'
g++ -std=c++11 -pedantic -Wall -Wextra -Wno-overloaded-virtual   -isystem /usr/include/hdf5 -c BufferedHDF2DArray.cpp -o BufferedHDF2DArray.o
g++ -std=c++11 -pedantic -Wall -Wextra -Wno-overloaded-virtual   -isystem /usr/include/hdf5 -c BufferedHDFArray.cpp -o BufferedHDFArray.o
g++ -std=c++11 -pedantic -Wall -Wextra -Wno-overloaded-virtual   -isystem /usr/include/hdf5 -c DatasetCollection.cpp -o DatasetCollection.o
g++ -std=c++11 -pedantic -Wall -Wextra -Wno-overloaded-virtual   -isystem /usr/include/hdf5 -c HDFAlnGroupGroup.cpp -o HDFAlnGroupGroup.o
In file included from HDFData.hpp:7:0,
                 from BufferedHDFArray.hpp:15,
                 from BufferedHDFArray.cpp:1:
HDFGroup.hpp:9:24: fatal error: H5Location.h: No such file or directory
 #include <H5Location.h>
                        ^
compilation terminated.
In file included from HDFData.hpp:7:0,
                 from BufferedHDF2DArray.hpp:12,
                 from BufferedHDF2DArray.cpp:1:
HDFGroup.hpp:9:24: fatal error: H5Location.h: No such file or directory
 #include <H5Location.h>
                        ^
compilation terminated.
In file included from HDFData.hpp:7:0,
                 from HDFArray.hpp:10,
                 from HDFAlnGroupGroup.hpp:5,
                 from HDFAlnGroupGroup.cpp:1:
HDFGroup.hpp:9:24: fatal error: H5Location.h: No such file or directory
 #include <H5Location.h>
                        ^
compilation terminated.
In file included from DatasetCollection.hpp:8:0,
                 from DatasetCollection.cpp:1:
HDFGroup.hpp:9:24: fatal error: H5Location.h: No such file or directory
 #include <H5Location.h>
                        ^
compilation terminated.
make[4]: *** [BufferedHDFArray.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [BufferedHDF2DArray.o] Error 1
make[4]: *** [HDFAlnGroupGroup.o] Error 1
make[4]: *** [DatasetCollection.o] Error 1
make[4]: Leaving directory `/home/ubuntu/alex/blasr/libcpp/hdf'
make[3]: *** [libpbihdf] Error 2
make[3]: Leaving directory `/home/ubuntu/alex/blasr/libcpp'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/ubuntu/alex/blasr/libcpp'
make[1]: *** [build-submodule] Error 2
make[1]: Leaving directory `/home/ubuntu/alex/blasr'
make: *** [init-submodule] Error 2
```

**Comment by mhsieh** [comment]
We probably need to know your HDF5 version, it can be obtained by this command: `dpkg --list|grep libhdf5-dev`

**Comment by alexfrieden** [comment]
```
$  dpkg --list|grep libhdf5-dev
ii  libhdf5-dev                          1.8.11-5ubuntu7                     amd64        Hierarchical Data Format 5 (HDF5) - development files - serial version
```

**Comment by mhsieh** [comment]
The version has to be >= 1.8.12 unfortunately.

**Comment by alexfrieden** [comment]
Any suggestions on how to install 1.8.12?

**Comment by mhsieh** [comment]
working on it for your ubuntu 14.04

**Comment by mhsieh** [comment]
I can't find a ubuntu repo for you yet, so I looked into the HDF5 website and found that they only provide centos support for the most recent release. But we can use prior version! 
Download this and extract it to somewhere (for example /home/ubuntu/alex/pacbio) you feel comfortable.
https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/bin/linux-x86_64-gnu482/hdf5-1.8.13-linux-x86_64-gnu482-static.tar.gz

add this to your configure.py arguments
`HDF5_LIB=/home/ubuntu/alex/pacbio/hdf5-1.8.13-linux-x86_64-gnu482-static/lib HDF5_INC=/home/ubuntu/alex/pacbio/hdf5-1.8.13-linux-x86_64-gnu482-static/include`

Let's see what happen.
Best,
--mj

**Comment by alexfrieden** [comment]
Okay, now getting new error:
```
...
g++ -std=c++11 -pedantic -Wall -Wextra -Wno-overloaded-virtual   -isystem /home/ubuntu/alex/hdf5-1.8.13-linux-x86_64-gnu482-static/include/ -fPIC -c HDFZMWWriter.cpp -o HDFZMWWriter.shared.o
ar rc libpbihdf.a BufferedHDF2DArray.o BufferedHDFArray.o DatasetCollection.o HDFAlnGroupGroup.o HDFAlnInfoGroup.o HDFAtom.o HDFAttributable.o HDFBaseCallsWriter.o HDFBaxWriter.o HDFCmpExperimentGroup.o HDFCmpSupportedFields.o HDFData.o HDFFile.o HDFGroup.o HDFNewBasReader.o HDFPulseCallsWriter.o HDFPulseDataFile.o HDFPulseH5Writer.o HDFPulseWriter.o HDFRegionsWriter.o HDFRegionTableReader.o HDFScanDataReader.o HDFScanDataWriter.o HDFUtils.o HDFWriterBase.o HDFZMWMetricsWriter.o HDFZMWReader.o HDFZMWWriter.o
g++ -shared  -L../pbdata -L/home/ubuntu/alex/hdf5-1.8.13-linux-x86_64-gnu482-static/lib -o libpbihdf.so -Wl,-soname,libpbihdf.so BufferedHDF2DArray.shared.o BufferedHDFArray.shared.o DatasetCollection.shared.o HDFAlnGroupGroup.shared.o HDFAlnInfoGroup.shared.o HDFAtom.shared.o HDFAttributable.shared.o HDFBaseCallsWriter.shared.o HDFBaxWriter.shared.o HDFCmpExperimentGroup.shared.o HDFCmpSupportedFields.shared.o HDFData.shared.o HDFFile.shared.o HDFGroup.shared.o HDFNewBasReader.shared.o HDFPulseCallsWriter.shared.o HDFPulseDataFile.shared.o HDFPulseH5Writer.shared.o HDFPulseWriter.shared.o HDFRegionsWriter.shared.o HDFRegionTableReader.shared.o HDFScanDataReader.shared.o HDFScanDataWriter.shared.o HDFUtils.shared.o HDFWriterBase.shared.o HDFZMWMetricsWriter.shared.o HDFZMWReader.shared.o HDFZMWWriter.shared.o -lpbdata -lhdf5 -lhdf5_cpp
/usr/bin/ld: /home/ubuntu/alex/hdf5-1.8.13-linux-x86_64-gnu482-static/lib/libhdf5.a(H5.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/ubuntu/alex/hdf5-1.8.13-linux-x86_64-gnu482-static/lib/libhdf5.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[4]: *** [libpbihdf.so] Error 1
make[4]: Leaving directory `/home/ubuntu/alex/blasr/libcpp/hdf'
make[3]: *** [libpbihdf] Error 2
make[3]: Leaving directory `/home/ubuntu/alex/blasr/libcpp'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/ubuntu/alex/blasr/libcpp'
make[1]: *** [build-submodule] Error 2
make[1]: Leaving directory `/home/ubuntu/alex/blasr'
make: *** [init-submodule] Error 2
```

**Comment by mhsieh** [comment]
I got the wrong tarball, can you use https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/bin/linux-x86_64-gnu482/hdf5-1.8.13-linux-x86_64-gnu482-shared.tar.gz instead? I can follow up after you got it build.

**Comment by alexfrieden** [comment]
@mhsieh it seems to have installed.  However, when I go to run:
```
$ ./blasr
./blasr: error while loading shared libraries: libpbihdf.so: cannot open shared object file: No such file or directory
```
I get this error.

**Comment by mhsieh** [comment]
Yes, that's why I said I need to follow up. See if this works for you:
```LD_LIBRARY_PATH=/home/ubuntu/alex/hdf5-1.8.13-linux-x86_64-gnu482-shared/lib ./blasr```

**Comment by alexfrieden** [comment]
same error still.

**Comment by mhsieh** [comment]
Hi Alex, does `/home/ubuntu/alex/hdf5-1.8.13-linux-x86_64-gnu482-shared/lib/libhdf5.so` file exist ?

**Comment by pb-cdunn** [comment]
This is a different problem. `libpbihdf.so` is built from blasr_libcpp. You just need to add the blasr_libcpp lib paths into `LD_LIBRARY_PATH`. There is no automatic way for us to do this. You have to decide how you are building/installing blasr_libcpp, which is a submodule of blasr but could also be installed separately, if you so choose.

We used to build static binaries to avoid these questions, but we cannot do that on OSX. So you need to set your own LD_LIBRARY_PATH.

**Comment by mhsieh** [comment]
Sorry that I misread the filename.

**Comment by vrainish-pacbio** [comment]
Hi Alex ,

It has been over a month since the last comment. If your problem still persist,
please follow recently added page on wiki "step by step blasr installation example".

It will ensure you have most updated blasr/libraries and clean hdf5
Perform it in separate directory and see if your blasr is built successfully.

**Comment by jfalkner** [comment]
This issue ended up being handy. I have a Vagrant-based setup on a vanilla Ubuntu 14.04 install that requires `blasr`. The HDF5 packaging for CentOS stinks. I only figured it out at the very end. Otherwise I'd just have used CentOS7.

I ended up compiling and getting a working `blasr` 14.04 install by using these commands.

```bash
# Setup working dir
DIR=/vagrant/smrtlink-eolqc/
mkdir -p $DIR
cd $DIR
git checkout https://github.com/PacificBiosciences/blasr.git
cd blasr
mkdir todelete
# Last non-CentOS binary that it seems HDF group made
wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/bin/linux-x86_64/hdf5-1.8.13-linux-x86_64-shared.tar.gz
tar -xf hdf5-1.8.13-linux-x86_64-shared.tar.gz

# Export HDF5_INCLUDE and HDF5_LIB
export HDF5_INCLUDE=/pbi/dept/itg/smrtlink-eolqc/blasr/todelete/hdf5-1.8.13-linux-x86_64-shared/include
export HDF5_LIB=/pbi/dept/itg/smrtlink-eolqc/blasr/todelete/hdf5-1.8.13-linux-x86_64-shared/lib

# Make blasr
cd $DIR/blasr
./configure.py --shared --sub --no-pbbam
make configure-submodule
make build-submodule
make blasr

# Run blasr with full LD_LIBRARY path that compiler used
LD_LIBRARY_PATH=$DIR/blasr/libcpp/alignment:$DIR/blasr/libcpp/hdf:$DIR/blasr/libcpp/pbdata:$DIR/blasr/todelete/hdf5-1.8.13-linux-x86_64-shared/lib ./blasr

#blasr - a program to map reads to a genome
# usage: blasr reads genome
# Run with -h for a list of commands
#          -help for verbose discussion of how to run blasr.
#
#In release v5.1 of BLASR, command-line options will use the
#single dash/double dash convention:
#Character options are preceded by a single dash. (Example: -v)
#Word options are preceded by a double dash. (Example: --verbose)
#Please modify your scripts accordingly when BLASR v5.1 is released.
```

**Comment by alexfrieden** [comment]
Thanks @jfalkner, we ended up just using an applet built on dnanexus as I couldn't get it working.  Next time I have to do this I will definitely follow your instructions!

**Comment by jfalkner** [comment]
It may have been a false hope though. `blasr` runs for me but blows up with this message: 

```
[INFO] 2016-09-20T18:04:35 [blasr] started.
ERROR! Hit unreachable code in files/ReaderAgglomerate.cpp:293
blasr: files/ReaderAgglomerate.cpp:293: int ReaderAgglomerate::Initialize(bool): Assertion `0' failed.
Aborted (core dumped)
```

That is on the latest commit. I'm going to try out older versions.

**Comment by jfalkner** [comment]
Interstingly, I just saw this too https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example

**Comment by heriosousa** [comment]
@jfalkner The tutorial in this link did not work for me. Got the error

`HDFGroup.hpp:9:24: fatal error: H5Location.h: No such file or directory`

Also, in your instructions, the command

`git checkout https://github.com/PacificBiosciences/blasr.git`

Gives me the following error

`error: pathspec 'https://github.com/PacificBiosciences/blasr.git' did not match any file(s) known to git.`

I'm not familiarized with git, what am I possibly doing wrong?

**Comment by vrainish-pacbio** [comment]
Hi 

It's not *git checkout* it's *git clone* below is the full command

*git clone https://github.com/PacificBiosciences/blasr.git --recursive*

**Comment by heriosousa** [comment]
@vrainish-pacbio Thank you for the help! Still got the same error, though.

**Comment by vrainish-pacbio** [comment]
Can you please, follow 'step by step installation example' under blasr wiki as it and let me know if you are able to complete it. Disregard other tutorial. Also, I don't understand 'the same error. Do you mean git clone generates the same error as git checkout?

**Comment by heriosousa** [comment]
@vrainish-pacbio I have followed the step-by-step installation at wiki and the other tutorial from @jfalkner. Both of them generated the same error after executing make build-submodule:

`HDFGroup.hpp:9:24: fatal error: H5Location.h: No such file or directory`

**Comment by vrainish-pacbio** [comment]
Let me check

**Comment by vrainish-pacbio** [comment]
I've just installed blsr from scratch following 'step by step' . No problems at all with HDFGroup..

Below is wget command 
wget https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/bin/linux-centos6-x86_64-gcc447/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared.tar.gz
--2016-10-17 14:08:44--  https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/bin/linux-centos6-x86_64-gcc447/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared.tar.gz
Resolving www.hdfgroup.org (www.hdfgroup.org)... 161.47.20.161, 2001:4801:7905:100:aff8:a2d8:0:1019
Connecting to www.hdfgroup.org (www.hdfgroup.org)|161.47.20.161|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/bin/linux-centos6-x86_64-gcc447/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared.tar.gz [following]
--2016-10-17 14:08:45--  https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/bin/linux-centos6-x86_64-gcc447/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared.tar.gz
Resolving support.hdfgroup.org (support.hdfgroup.org)... 50.28.50.143
Connecting to support.hdfgroup.org (support.hdfgroup.org)|50.28.50.143|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27878491 (27M) [application/x-gzip]
Saving to: ‘hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared.tar.gz’

Please, make sure your configure.py lists paths correctly, see belkow

./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=${TOP}/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/ HDF5_LIB=${TOP}/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/lib

**Comment by heriosousa** [comment]
It finally worked, thanks for the help, @vrainish-pacbio

**Comment by vrainish-pacbio** [comment]
No problem, you welcome .  Please, be advised that you might need to install blasr via pitchfork ( to ensure its built with pbbam ) in order to be able to generate sam/bam output ( 'step by step' installs blasr WITHOUT pbbam, it intends to check basic functionality only )

**Comment by heriosousa** [comment]
How could I do that?

**Comment by vrainish-pacbio** [comment]
clone
 
https://github.com/PacificBiosciences/pitchfork

follow wiki there

You **DON'T** need to bring hdf5 , pbbam, run configure.py etc, pitchfork does everything for you

after 

make blasr
 
and EXPORT LD_LIBRARY_PATH

you will have blasr with pbbam support

Post here if you have problems.

Since you've managed to install standalone blasr , it should be OK
