### ISSUE TITLE
master does not build on ubuntu 14.04 , stepping back a few commits does build.

### ISSUE THREAD

**Issue by bwlang** [PacificBiosciences/blasr#163]
@ylipacbio  I think this may be related to recent cleanup commits 
```
g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
```
I went back to 
git checkout a1b43cafc0bc5257b22eaa542d65cf69c35e3a5a
and the build went fine.

sorry - i don't have time to bisect right now.

here is the error I see:

```
g++ -O3 -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/mnt/home/langhorst/src/blasr/libcpp/alignment -I/mnt/home/langhorst/src/blasr/libcpp/hdf -I/mnt/home/langhorst/src/blasr/libcpp/pbdata -isystem/mnt/home/langhorst/include  -c -o Blasr.o Blasr.cpp
In file included from iblasr/BlasrAlign.hpp:85:0,
                 from iblasr/BlasrUtilsImpl.hpp:4,
                 from iblasr/BlasrUtils.hpp:162,
                 from Blasr.cpp:4:
iblasr/BlasrAlignImpl.hpp: In function ‘void MapRead(T_Sequence&, T_Sequence&, T_RefSequence&, T_SuffixArray&, BWT&, SeqBoundaryFtr<FASTQSequence>&, T_TupleCountTable&, SequenceIndexDatabase<FASTQSequence>&, MappingParameters&, MappingMetrics&, std::vector<AlignmentCandidate<DNASequence, FASTQSequence>*>&, MappingBuffers&, MappingIPC*, MappingSemaphores&)’:
iblasr/BlasrAlignImpl.hpp:409:80: error: ‘PacBio::AnchorDistributionTable’ has not been declared
         int boundedMinWordMatchLength = min(max(params.minMatchLength, PacBio::AnchorDistributionTable::anchorMinKValues[0]), PacBio::AnchorDistributionTable::anchorMinKValues[1]);
                                                                                ^
iblasr/BlasrAlignImpl.hpp:409:135: error: ‘PacBio::AnchorDistributionTable’ has not been declared
         int boundedMinWordMatchLength = min(max(params.minMatchLength, PacBio::AnchorDistributionTable::anchorMinKValues[0]), PacBio::AnchorDistributionTable::anchorMinKValues[1]);
                                                                                                                                       ^
iblasr/BlasrAlignImpl.hpp:414:95: error: ‘PacBio::AnchorDistributionTable’ has not been declared
         int boundedMatchLength  = min(max((int) alignmentPtrs[0]->qAlignedSeq.length, PacBio::AnchorDistributionTable::anchorReadLengths[0]), PacBio::AnchorDistributionTable::anchorReadLengths[1]);
                                                                                               ^
iblasr/BlasrAlignImpl.hpp:414:151: error: ‘PacBio::AnchorDistributionTable’ has not been declared
         int boundedMatchLength  = min(max((int) alignmentPtrs[0]->qAlignedSeq.length, PacBio::AnchorDistributionTable::anchorReadLengths[0]), PacBio::AnchorDistributionTable::anchorReadLengths[1]);
                                                                                                                                                       ^
iblasr/BlasrAlignImpl.hpp:415:90: error: ‘PacBio::AnchorDistributionTable’ has not been declared
         int boundedPctSimilarity = min(max((int)alignmentPtrs[0]->pctSimilarity, PacBio::AnchorDistributionTable::anchorReadAccuracies[0]), PacBio::AnchorDistributionTable::anchorReadAccuracies[1]);
                                                                                          ^
iblasr/BlasrAlignImpl.hpp:415:149: error: ‘PacBio::AnchorDistributionTable’ has not been declared
         int boundedPctSimilarity = min(max((int)alignmentPtrs[0]->pctSimilarity, PacBio::AnchorDistributionTable::anchorReadAccuracies[0]), PacBio::AnchorDistributionTable::anchorReadAccuracies[1]);

```

(and a wall of warnings)

**Comment by pb-cdunn** [comment]
This should work now, after you run `git submodule update`.
