### ISSUE TITLE
cannot build with Xcode 8 due to clock_gettime

### ISSUE THREAD

**Issue by ilovezfs** [PacificBiosciences/blasr#322]
I'm working around the `clock_gettime` problems with the following:

```
    inreplace ["libcpp/alignment/MappingMetrics.cpp",
               "libcpp/alignment/MappingMetrics.hpp"] do |s|
      if MacOS.version >= :sierra
        s.gsub! "#ifdef __APPLE__", "#ifdef __OPPLE__"
      else
        s.gsub! "CLOCK_", "MYCLOCK_"
        s.gsub! "clockid_t", "myclockid_t"
      end
    end
```

Note that there are two distinct failure scenarios here with Xcode 8, which is used now on macOS 10.11 and 10.12.

For 10.12, blasr incorrectly assumes that macOS does not support clock_gettime. This is no longer true as of Sierra, which added clock_gettime support. So `s.gsub! "#ifdef __APPLE__", "#ifdef __OPPLE__"` disables the Apple specific code since it is not applicable to 10.12 and above.

For 10.11, the situation is more complicated. Apple uses a unitary Xcode 8 SDK intended for compiling on 10.11 and 10.12. As a result, functions which are newly available on 10.12 are marked as "weak" for 10.11, which means that although they are defined in the headers, they are not actually available for use unless you're executing on >= 10.12.

This means that on 10.11, although clock_gettime is not available to be called, it is already defined in the SDK. Therefore, the blasr compatibility implementation of clock_gettime collides with the already defined clock_gettime and associated enums and constants. The workaround 
```
        s.gsub! "CLOCK_", "MYCLOCK_"
        s.gsub! "clockid_t", "myclockid_t"
```
avoids redefining those symbols while still providing the necessary compatibility implementation.

The build failure on 10.11 looks like this:
```
clang++ -dynamiclib -flat_namespace -L../pbdata -L/usr/local/opt/hdf5/lib -o libpbihdf.dylib -Wl,-install_name,libpbihdf.dylib BufferedHDF2DArray.shared.o BufferedHDFArray.shared.o DatasetCollection.shared.o HDFAlnGroupGroup.shared.o HDFAlnInfoGroup.shared.o HDFAtom.shared.o HDFAttributable.shared.o HDFBaseCallsWriter.shared.o HDFBaxWriter.shared.o HDFCmpExperimentGroup.shared.o HDFCmpSupportedFields.shared.o HDFData.shared.o HDFFile.shared.o HDFGroup.shared.o HDFNewBasReader.shared.o HDFPulseCallsWriter.shared.o HDFPulseDataFile.shared.o HDFPulseH5Writer.shared.o HDFPulseWriter.shared.o HDFRegionTableReader.shared.o HDFRegionsWriter.shared.o HDFScanDataReader.shared.o HDFScanDataWriter.shared.o HDFUtils.shared.o HDFWriterBase.shared.o HDFZMWMetricsWriter.shared.o HDFZMWReader.shared.o HDFZMWWriter.shared.o -lpbdata -lhdf5 -lhdf5_cpp
/Applications/Xcode.app/Contents/Developer/usr/bin/make libblasr
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /private/tmp/blasr-20161225-55397-1bpb35u/libcpp//alignment all
clang++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual   -I/usr/local/opt/hdf5/include  -c MappingMetrics.cpp -o MappingMetrics.o
In file included from MappingMetrics.cpp:3:
./MappingMetrics.hpp:16:5: error: redefinition of enumerator '_CLOCK_REALTIME'
    CLOCK_REALTIME,
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:154:24: note: expanded from macro 'CLOCK_REALTIME'
#define CLOCK_REALTIME _CLOCK_REALTIME
                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:153:1: note: previous definition is here
_CLOCK_REALTIME __CLOCK_AVAILABILITY = 0,
^
In file included from MappingMetrics.cpp:3:
./MappingMetrics.hpp:17:5: error: redefinition of enumerator '_CLOCK_MONOTONIC'
    CLOCK_MONOTONIC,
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:156:25: note: expanded from macro 'CLOCK_MONOTONIC'
#define CLOCK_MONOTONIC _CLOCK_MONOTONIC
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:155:1: note: previous definition is here
_CLOCK_MONOTONIC __CLOCK_AVAILABILITY = 6,
^
In file included from MappingMetrics.cpp:3:
./MappingMetrics.hpp:18:5: error: redefinition of enumerator '_CLOCK_PROCESS_CPUTIME_ID'
    CLOCK_PROCESS_CPUTIME_ID,
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:168:34: note: expanded from macro 'CLOCK_PROCESS_CPUTIME_ID'
#define CLOCK_PROCESS_CPUTIME_ID _CLOCK_PROCESS_CPUTIME_ID
                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:167:1: note: previous definition is here
_CLOCK_PROCESS_CPUTIME_ID __CLOCK_AVAILABILITY = 12,
^
In file included from MappingMetrics.cpp:3:
./MappingMetrics.hpp:19:5: error: redefinition of enumerator '_CLOCK_THREAD_CPUTIME_ID'
    CLOCK_THREAD_CPUTIME_ID
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:170:33: note: expanded from macro 'CLOCK_THREAD_CPUTIME_ID'
#define CLOCK_THREAD_CPUTIME_ID _CLOCK_THREAD_CPUTIME_ID
                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:169:1: note: previous definition is here
_CLOCK_THREAD_CPUTIME_ID __CLOCK_AVAILABILITY = 16
^
In file included from MappingMetrics.cpp:3:
./MappingMetrics.hpp:20:3: error: typedef redefinition with different types ('enum clockid_t' vs 'enum clockid_t')
} clockid_t;
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:171:3: note: previous definition is here
} clockid_t;
  ^
5 errors generated.
make[3]: *** [MappingMetrics.o] Error 1
make[2]: *** [libblasr] Error 2
make[1]: *** [all] Error 2
make: *** [build-submodule] Error 2
```

Full build log: https://gist.github.com/ilovezfs/2c86f55e60b75a2ea71ee67ecfad85a9

**Comment by mjhsieh** [comment]
see https://github.com/PacificBiosciences/blasr_libcpp/commit/4ece590ab4b03aaec3033d0eabcce4bcdc52d111

**Comment by ilovezfs** [comment]
@mjhsieh sure, but that doesn't fix 10.11.

**Comment by mjhsieh** [comment]
Okay I will do that one byte change.

**Comment by mjhsieh** [comment]
PacificBiosciences/blasr_libcpp@4b3e979c7f61be0096a0b0772c0c2910f3b05783

**Comment by ilovezfs** [comment]
I think you've misunderstood the above. 10.11 still needs the compatibility implementation. The problem is that it cannot have the same name.

**Comment by ilovezfs** [comment]
@mjhsieh here are examples of proper fixes for 10.11 + Xcode 8 SDK issues:

https://github.com/jsquyres/libfabric/commit/469779935f9995b88a6f486fe3c4c4496989af36.
https://github.com/tarantool/tarantool/commit/d36ba2796839db0edd3c62e9048cd41b1ee08d1e
https://github.com/jemalloc/jemalloc/commit/eb29d7ec0e2c4994e10ec40d42265a86e569500c

**Comment by mjhsieh** [comment]
I only removed the clockid_t definition for version >= 10.11, not the whole clock_gettime

**Comment by mjhsieh** [comment]
That being said, I only tested the build, not the blasr itself, the renaming is easy to do and safe from implementing the official code.

**Comment by ilovezfs** [comment]
Do you also have the Xcode command line tools installed? That may be confusing the situation.

**Comment by mjhsieh** [comment]
Yes I also have the command line tools installed.

**Comment by ilovezfs** [comment]
Yeah, the headers in the CLT are different and will mask the bug entirely.

The failure scenario on 10.11 is when you

a) have only Xcode 8, or
b) have both Xcode 8 and the CLT, and set the SDKROOT to the Xcode SDK folder.

You can reproduce the issue (as I just did https://gist.github.com/ilovezfs/26029b23c7854249960d7f2cc6e24479) by setting
```
export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
```
before building.

**Comment by ilovezfs** [comment]
Note you should also set `export MACOSX_DEPLOYMENT_TARGET=10.11`

**Comment by mjhsieh** [comment]
Why would you use 10.12.sdk on a 10.11 machine? Apology for my ignorance not following all the toolchain issue on the Mac. At this moment I am about to drop my attempt to support mac.

**Comment by ilovezfs** [comment]
@mjhsieh It is normal.

As of Xcode 7 and above there's only one SDK per Xcode. They just call it by the name of the latest version of macOS. So the single SDK in Xcode 8 is called "10.12" and the single SDK in Xcode 7 is called "10.11" and so forth.

You can see that 10.11 is specifically referenced in the Xcode 8 SDK regarding these weak symbols
```
iMac-TMP:~ joe$ grep 'weak$os10.11' /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/system/libsystem_c.tbd
    symbols:         [ '$ld$weak$os10.11$_basename_r', '$ld$weak$os10.11$_clock_getres', 
                       '$ld$weak$os10.11$_clock_gettime', '$ld$weak$os10.11$_clock_settime', 
                       '$ld$weak$os10.11$_dirname_r', '$ld$weak$os10.11$_getentropy', 
                       '$ld$weak$os10.11$_mkostemp', '$ld$weak$os10.11$_mkostemps', 
```
since there is now a feature `-no_weak_imports` intended for handling these cases.

In fact as of Xcode 8, the SDK folder is `MacOSX.sdk` and `MacOSX10.12.sdk` is just a symlink to avoid breaking build systems that assume there will be a number there:
```
iMac-TMP:~ joe$ ls -al /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
total 8
drwxr-xr-x@ 3 joe  admin  136 Oct 29 01:47 .
drwxr-xr-x@ 5 joe  admin  170 Oct 13 20:41 ..
drwxr-xr-x@ 4 joe  admin  170 Jan 27  2019 MacOSX.sdk
lrwxr-xr-x  1 joe  admin   10 Oct 29 01:46 MacOSX10.12.sdk -> MacOSX.sdk
```
You may find these links helpful
You may find these helpful:

Why You Should Use the Latest SDK:
https://developer.apple.com/library/content/qa/qa1806/_index.html

Setting the Base SDK:
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ConfiguringYourApp/ConfiguringYourApp.html#//apple_ref/doc/uid/TP40012582-CH28-SW37

Setting the Deployment Target:
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ConfiguringYourApp/ConfiguringYourApp.html#//apple_ref/doc/uid/TP40012582-CH28-SW21

I would strongly encourage you not to drop macOS support. The solution here is just to use a name other than "clock_gettime" for the compatibility function so that you don't have symbol collision.

**Comment by mjhsieh** [comment]
So the core problem here is that MAC_OS_X_VERSION_MIN_REQUIRED is not sufficient.

**Comment by ilovezfs** [comment]
Right. Setting the deployment target (setting MACOSX_DEPLOYMENT_TARGET or passing `mmacosx-version-min`) is necessary when using latest SDK but not sufficient. You also have to make sure to heed weak imports that can be defined in the header but not present in the library. Thankfully there aren't very many for 10.11 (basename_r, clock_getres, clock_gettime, clock_settime, dirname_r, getentropy, mkostemp, mkostemps).

**Comment by ilovezfs** [comment]
@mjhsieh if it makes you feel any better, this is not an uncommon issue: https://github.com/Homebrew/homebrew-core/issues?utf8=%E2%9C%93&q=label%3Aclock_gettime

**Comment by mjhsieh** [comment]
I think MAC_OS_X_VERSION_MAX_ALLOWED should be used here. Working on that.

**Comment by mjhsieh** [comment]
```
mjhsieh$ cat test.c 
#include <stdio.h>
#include <AvailabilityMacros.h>
int main(){
	printf ("__APPLE__: %d\n", __APPLE__);
	printf ("MAC_OS_X_VERSION_10_11: %d\n",        MAC_OS_X_VERSION_10_11);
	printf ("MAC_OS_X_VERSION_MAX_ALLOWED: %d\n",  MAC_OS_X_VERSION_MAX_ALLOWED);
	printf ("MAC_OS_X_VERSION_MIN_REQUIRED: %d\n", MAC_OS_X_VERSION_MIN_REQUIRED);
	return 0;
}
mjhsieh$ unset MACOSX_DEPLOYMENT_TARGET SDKROOT
mjhsieh$ gcc test.c -o ./test.exe && ./test.exe||echo no
__APPLE__: 1
MAC_OS_X_VERSION_10_11: 101100
MAC_OS_X_VERSION_MAX_ALLOWED: 101104
MAC_OS_X_VERSION_MIN_REQUIRED: 101100
mjhsieh$ SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk MACOSX_DEPLOYMENT_TARGET=10.11 gcc test.c -o ./test.exe && ./test.exe||echo no
__APPLE__: 1
MAC_OS_X_VERSION_10_11: 101100
MAC_OS_X_VERSION_MAX_ALLOWED: 101201
MAC_OS_X_VERSION_MIN_REQUIRED: 101100
```

**Comment by mjhsieh** [comment]
https://github.com/PacificBiosciences/blasr_libcpp/commit/9401408fefe8b9b27124b36ddc9beb0c85175779

**Comment by ilovezfs** [comment]
As I said above, it needs to have a _different_ name. Your current code produces
```
$ nm /usr/local/Cellar/blasr-libcpp/HEAD-9401408/libexec/alignment/libblasr.dylib|grep clock
                 U _clock_gettime
```
which will cause problems since that symbol is explicitly marked as weak for 10.11.

**Comment by mjhsieh** [comment]
I probably am wrong here, but this "accidental strong clock_gettime" should override the weak clock_gettime from 10.11 don't you think?

**Comment by ilovezfs** [comment]
Unfortunately, it can still cause problems, as here: https://github.com/Homebrew/homebrew-core/issues/5011

**Comment by mjhsieh** [comment]
okay feel free to do whatever replacement you want in ruby. I don't think I will do more outside __APPLE__

**Comment by mjhsieh** [comment]
However even so I might need to change it to my_clock_gettime to make it easier to replace. For something like this
```ruby
    cd "alignment" do
      inreplace %w[MappingMetrics.cpp],
        "clock_gettime", "my_clock_gettime"
    end
```

**Comment by mjhsieh** [comment]
(I squashed some of my attempts, so you might need to merge the conflict, apologies.) current status:
```shell
mjhsieh$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G1212
mjhsieh$ nm deployment/lib/libblasr.dylib | grep clock_gettime
00000000000cdc50 T __Z17my_clock_gettime_9clockid_tP8timespec
00000000002ec240 b __ZL19__clock_gettime_inf
```

**Comment by ilovezfs** [comment]
```
bash-3.2$ cat foo.cpp 
#include "/usr/local/opt/blasr-libcpp/include/alignment/MappingMetrics.hpp"

int main() {
	Timer *t = new Timer();
	t->Tick();
	return 0;
}
bash-3.2$ clang++ foo.cpp -o foo -L/usr/local/opt/blasr-libcpp/lib -lblasr
bash-3.2$ ./foo
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/blasr-libcpp/lib/libblasr.dylib
  Expected in: flat namespace

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/blasr-libcpp/lib/libblasr.dylib
  Expected in: flat namespace

Trace/BPT trap: 5
bash-3.2$ echo $SDKROOT
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
bash-3.2$ echo $MACOSX_DEPLOYMENT_TARGET
10.11
bash-3.2$
```
That's acceptable to you?

**Comment by mjhsieh** [comment]
You might need to update the libblasr_cpp source. As to the acceptance of your test result earlier, that's apparently not acceptable if I want to work on blasr in my old 10.11 box. Note: there is no plan for us to support mac as a platform of our software. You are talking to one of handful people (<5) that will go extra mile to do something about the mac. It's still up to the port maintainer to fix it.

**Comment by ilovezfs** [comment]
Building from fd288b6f36062b7677b2bbd16f5a29862cbe7b59:
https://gist.github.com/ilovezfs/5f1afb42a296316f655a3c95ac73a589

**Comment by mjhsieh** [comment]
```
mjhsieh$ cat test2.cpp
#include "blasr_libcpp/alignment/MappingMetrics.hpp"

int main() {
Timer *t = new Timer();
t->Tick();
return 0;
}
mjhsieh$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G1212
mjhsieh$ clang++ test2.cpp -o foo -L$PWD/deployment/lib -lblasr
mjhsieh$ SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk MACOSX_DEPLOYMENT_TARGET=10.11 clang++ test2.cpp -o foo -L$PWD/deployment/lib -lblasr
```

**Comment by mjhsieh** [comment]
You are almost there
```
mjhsieh$ DYLD_LIBRARY_PATH=deployment/lib ./foo && echo yes
yes
```

**Comment by ilovezfs** [comment]
Is that with a string replacement?
fd288b6f36062b7677b2bbd16f5a29862cbe7b59 gives
```
iMac-TMP:homebrew-science joe$ SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk MACOSX_DEPLOYMENT_TARGET=10.11 clang++ test2.cpp -o foo -L/usr/local/Cellar/blasr-libcpp/4.0.0/lib -lblasr
iMac-TMP:homebrew-science joe$ ./foo
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/blasr-libcpp/lib/libblasr.dylib
  Expected in: flat namespace

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/blasr-libcpp/lib/libblasr.dylib
  Expected in: flat namespace

Trace/BPT trap: 5
iMac-TMP:homebrew-science joe$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1108
```

**Comment by ilovezfs** [comment]
Not necessary:
```
iMac-TMP:homebrew-science joe$ otool -L foo
foo:
	/usr/local/opt/blasr-libcpp/lib/libblasr.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

**Comment by mjhsieh** [comment]
```
mjhsieh$ DYLD_LIBRARY_PATH=deployment/lib otool -L foo 
foo:
        libblasr.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

**Comment by mjhsieh** [comment]
Who made that port anyway?

**Comment by ilovezfs** [comment]
```
iMac-TMP:homebrew-science joe$ nm foo
0000000100000f28 s GCC_except_table0
                 U __Unwind_Resume
                 U __ZN5Timer4TickEv
                 U __ZN5TimerC1ENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
0000000100000e70 t __ZNSt3__111char_traitsIcE6lengthEPKc
                 U __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcm
                 U __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev
                 U __ZSt9terminatev
                 U __ZdlPv
                 U __Znwm
0000000100000e60 t ___clang_call_terminate
                 U ___cxa_begin_catch
                 U ___gxx_personality_v0
0000000100000000 T __mh_execute_header
0000000100000cf0 T _main
                 U _strlen
                 U dyld_stub_binder
iMac-TMP:homebrew-science joe$ nm /usr/local/opt/blasr-libcpp/lib/libblasr.dylib|grep clock
                 U _clock_gettime

```

**Comment by mjhsieh** [comment]
```
mjhsieh$ nm foo
0000000100000f28 s GCC_except_table0
                 U __Unwind_Resume
                 U __ZN5Timer4TickEv
                 U __ZN5TimerC1ENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
0000000100000e70 t __ZNSt3__111char_traitsIcE6lengthEPKc
                 U __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcm
                 U __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev
                 U __ZSt9terminatev
                 U __ZdlPv
                 U __Znwm
0000000100000e60 t ___clang_call_terminate
                 U ___cxa_begin_catch
                 U ___gxx_personality_v0
0000000100000000 T __mh_execute_header
0000000100000cf0 T _main
                 U _strlen
                 U dyld_stub_binder
mjhsieh$ nm deployment/lib/libblasr.dylib |grep clock
00000000000cdc50 T __Z17my_clock_gettime_9clockid_tP8timespec
00000000002ec240 b __ZL19__clock_gettime_inf
                 U _clock_get_time
                 U _host_get_clock_service
```

**Comment by ilovezfs** [comment]
I made it just now to test:
```
brew cat blasr-libcppiMac-TMP:~ joe$ brew cat blasr-libcpp
class BlasrLibcpp < Formula
  url "https://github.com/PacificBiosciences/blasr_libcpp.git",
      :revision => "fd288b6f36062b7677b2bbd16f5a29862cbe7b59"
  version "4.0.0"
  head "https://github.com/PacificBiosciences/blasr_libcpp.git"

  depends_on "hdf5"

  def install
    ENV["HDF5_INCLUDE"] = Formula["hdf5"].opt_include
    ENV["HDF5_LIB"] = Formula["hdf5"].opt_lib

    system "sh", "-c", "NOPBBAM=1 ./configure.py"
    system "make", "all"
    lib.install %w[alignment/libblasr.dylib pbdata/libpbdata.dylib hdf/libpbihdf.dylib]
    include.install buildpath.children
  end
end
```

**Comment by ilovezfs** [comment]
```
mjhsieh$ nm deployment/lib/libblasr.dylib |grep clock
00000000000cdc50 T __Z17my_clock_gettime_9clockid_tP8timespec
00000000002ec240 b __ZL19__clock_gettime_inf
                 U _clock_get_time
                 U _host_get_clock_service
```
is definitely different hehe

**Comment by mjhsieh** [comment]
first of all you should see my_clock_gettime_ , if you don't see that you are using the old binary I presume?

**Comment by ilovezfs** [comment]
fd288b6f36062b7677b2bbd16f5a29862cbe7b59?

**Comment by ilovezfs** [comment]
Log is clear: https://gist.github.com/ilovezfs/5f1afb42a296316f655a3c95ac73a589

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda install -c bioconda blasr`
