### ISSUE TITLE
blasr fails to build with hdf5 1.10.1

### ISSUE THREAD

**Issue by iMichka** [PacificBiosciences/blasr#355]
Hi. We updated to the latest hdf5 version, and blasr fails to build due to some API changes in hdf5.

Here is a full build log:
https://gist.github.com/iMichka/188ecd68214814054ca423d01983e0a0

Here are some examples:
```cpp
../common/data/hdf/BufferedHDF2DArray.h:440:23: note: expanded from macro 'DEFINE_TYPED_CREATE'
        dataset = container->createDataSet(datasetName.c_str(), Pred, fileSpace, cparms);\
                  ~~~~~~~~~  ^
../common/data/hdf/BufferedHDF2DArray.h:447:1: error: no member named 'createDataSet' in 'H5::CommonFG'

In file included from BuildSequenceDB.cpp:5:
In file included from ./../common/utils/FileOfFileNames.h:8:
In file included from ../common/utils/../data/hdf/HDFNewBasReader.h:8:
In file included from ../common/utils/../data/hdf/HDFArray.h:10:
../common/utils/../data/hdf/HDFData.h:59:25: error: no member named 'openDataSet' in 'H5::CommonFG'
    dataset   = hdfFile.openDataSet(_datasetName.c_str());
                ~~~~~~~ ^
```
Could you have a look at this? Thanks.

**Comment by pb-cdunn** [comment]
Hmm. These seem to have moved from `CommonFG` (in `H5CommonFG.h`) to `Group` (in `H5Group.h`), in this commit:
* https://github.com/live-clones/hdf5/commit/c78f1ec8829e25672d738d6772a096f3eafd9295

But I cannot find the lines of blasr_libcpp you have referenced above. `hdf/BufferedHDF2DArray.hpp` is now less than 400 lines, `hdf/HDFData.hpp` is only 53 lines, and we no longer use `.h` extensions. I think you have somehow obtain a very old version of blasr/libcpp.

**Comment by iMichka** [comment]
Hi. Thanks for having looked at this. We are delivering release 2.2, which is marked as the last stable release on GitHub. I will try with the latest master to see if this is fixed. If that works we may need a new official release (if possible).

**Comment by lparsons** [comment]
I'm running into this issue using the latest ([`574e1c2`](https://github.com/PacificBiosciences/blasr/commit/574e1c2ab1fadea49774c61c2c2374006e941ec1)) revision of blasr.
The problem seems to be here: https://github.com/PacificBiosciences/blasr_libcpp/blob/master/hdf/BufferedHDF2DArray.cpp#L78

```
BufferedHDF2DArray.cpp: In member function ‘void BufferedHDF2DArray<T>::TypedCreate(H5::DataSpace&, H5::DSetCreatPropList&) [with T = short int]’:
BufferedHDF2DArray.cpp:78:30: error: ‘class H5::CommonFG’ has no member named ‘createDataSet’
         dataset = container->createDataSet(datasetName.c_str(), Pred, fileSpace, cparms); \
                              ^
```

**Comment by lparsons** [comment]
A new official release would be most welcome, btw, so we don't have to rely on github cloning in both homebrew and bioconda.

**Comment by asdcid** [comment]
same issue here..

**Comment by lparsons** [comment]
@pb-cdunn Any chance you could look at this issue again, I believe we're using up to date code and running into a build issue related to the HDF API version incompatibility.

**Comment by sjackman** [comment]
@lparsons Are you using 4.0.0 release of `blasr`? https://github.com/PacificBiosciences/blasr/archive/smrtanalysis-4.0.0.tar.gz

**Comment by outpaddling** [comment]
I'm getting this issue with the latest commit, b038971c97eb5403b982c177eb44e488d25e9994 and hdf5 1.10.1
What version of hdf5 are you guys using for internal builds?

**Comment by baberlevi** [comment]
agree - this is still an issue with latest blasr, blasr_libcpp, and pbbam. hdf5 1.10 does not work.

@pb-cdunn  - can this be reopened ?

**Comment by outpaddling** [comment]
The incompatibility between hdf5 1.8 and 1.10 is apparently a common problem, as the FreeBSD ports tree contains both the latest hdf5 (science/hdf5) and a legacy 1.8 port (science/hdf5-18).  Using the latter was an easy workaround for me on FreeBSD, but not all package managers offer this, and it's only a temporary fix.  Compatibility with hdf5 1.10 is definitely needed for the long term and 1.10 has been available for about 2 years now.  Thanks...

**Comment by sjackman** [comment]
@iMichka Homebrew/core has `hdf5@1.8`.

**Comment by iMichka** [comment]
I think `blasr` was not migrated to the new science repo, so it is not shipped anymore. Using `hdf5@1.8` would be a solution. I am not personally using `blasr` so I'll let other volunteers work on this if they need it :)

**Comment by armintoepfer** [comment]
We've stopped supporting source build problems. It doesn't scale.
Instead, we provide it via biaconda: `conda install -c bioconda blasr`

**Comment by sjackman** [comment]
Here's the Bioconda recipe:
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/blasr/5.3.1

**Comment by mchaisso** [comment]
I ran the above command to install blasr with miniconda, then when trying
to run, I use:

> conda activate
> blasr reads.fa ref.fa

Then have the error:
blasr: error while loading shared libraries: libpbihdf.so: cannot open
shared object file: No such file or directory

I'm sure this is misusing miniconda (it's my first conda use), but I then
added the conda lib and path to the blasr_libcpp to my LD_LIBRARY_PATH

export
LD_LIBRARY_PATH=/home/cmb-16/mjc/shared/miniconda/pkgs/blasr_libcpp-1.1-boost1.60_0/lib/

and get the error:

blasr: symbol lookup error: blasr: undefined symbol:
_ZN17ReaderAgglomerate10InitializeEb

(I also added .../miniconda/lib to the LD_LIBRARY_PATH with no avail).

Any suggestions?
Thanks,
-Mark

**Comment by sjackman** [comment]
Hi, Mark! I'm afraid that I'm not terribly well versed in Conda. You could try opening an issue on their GitHub page at https://github.com/bioconda/bioconda-recipes/issues/new

**Comment by outpaddling** [comment]
I can understand not wanting to support Joe Scientist attempting a caveman build, but if you look carefully at this thread you'll see that at least three contributors are developers for package managers (FreeBSD ports, Linuxbrew, and pkgsrc).  We're trying to make your software more accessible via a variety of package managers so that others don't have to do source builds.  All we're asking is that the code be updated to work with current libraries, which must be done periodically in any case.

**Comment by pb-dseifert** [comment]
@outpaddling 
Unfortunately, history tells us 80% of people trying to compile our software are Joe Scientists. Anyhow, we only use Meson now, and I am pretty certain that BLASR and friends can easily be built nowadays using Meson, give it a try if you like (look at the bioconda recipes to see how simple it is). If you find a **true** bug in our build system, feel free to send in a PR, but `LD_LIBRARY_PATH` issues and issues related to deployment will not be debugged for users.

@mchaisso The issue you're seeing is related to a interaction between an old artifact and how conda parses version tuples, erroneously thinking `5.3.9c6f0a5` is more recent than `5.3.1`, due to some int coercion. See https://github.com/PacificBiosciences/blasr/issues/396#issuecomment-395157179 for a temporary workaround, while the broken binary artifacts are still in the Anaconda cloud, which should be resolved soon.

To all others: since commit https://github.com/PacificBiosciences/blasr_libcpp/commit/c8b77dd327380c6f12f001e11ec4b3f3a5ea2f08 BLASR can be built with the latest hdf5 1.8.20 and 1.10.3, so that should clear things up.

**Comment by baberlevi** [comment]
Adding to what @outpaddling said - We were also building for a package manager (Spack), which we had successfully done based off your configure.py, just before your latest release. Thankfully, it was still included in your release, and a few minor tweaks kept that working with the released version (the release was appreciated btw). 

Unfortunately, now I see that the configure.py been removed post-release.  It would be helpful if there was some communication about expected changes to the build process so we plan for that.  

We'll give your meson build a try.

**Comment by pb-dseifert** [comment]
Sorry, we don't have the resources to provide a big roadmap with a long deprecation phase. The `configure.py` build system has always been painful and extremely brittle. Meson is extremely easy to use, fast, encapsulated, featureful and doesn't require complicated variable shuffling around.

**Comment by baberlevi** [comment]
I'm in favor of a better build process, but until literally 6 days ago (post release), all the documentation said to use cmake, pitchfork, or the configure.py/make process - there was no mention of meson.

FYI - you may want to update: https://github.com/PacificBiosciences/blasr/wiki/Blasr-Installation-Qs-&-As

**Comment by mhsieh** [comment]
Let me see what I can do. Yes I am also going to deprecate my pitchfork.

**Comment by mchaisso** [comment]
That's good to know.  Considering that it's getting close to the 10-year
anniversary of when the first blasr code was written (omg!), it is well
past retirement age.  Luckily blasr2 (real name tbd) is in the works. No
pesky hdf support though.

**Comment by mhsieh** [comment]
Mark, for now you might want to try `conda uninstall blasr` and `conda install blasr==5.3.1` if you have not done that already.

**Comment by mchaisso** [comment]
conda install -c bioconda blasr==5.3.1 did the trick.  Thanks!

**Comment by outpaddling** [comment]
What's this about Meson and LD_LIBRARY_PATH?  My only request was hdf5 1.10 compatibility.

**Comment by pb-dseifert** [comment]
...which BLASR does now. Joe Scientist will often encounter issues because blasr is installed into some weird location and won't find the libraries. My point was, we won't be helping users not being able to get BLASR to run and explaining environmental variables and such.

**Comment by pb-dseifert** [comment]
@mchaisso could you please retry `conda install -c bioconda blasr` (yes without the version specifier) with a fresh throw-away miniconda installation? I fixed the anaconda cloud version mixup, and the default should just work now and give you 5.3.2.

**Comment by mchaisso** [comment]
Worked like a charm.  What is the schedule for getting quiver/arrow up on
conda?

**Comment by armintoepfer** [comment]
Soon. It's on the to-do list.
